/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Users {
  createdAt: Generated<Timestamp | null>;
  email: string;
  firstName: string | null;
  id: string;
  kindeId: string;
  lastName: string | null;
  pictureUrl: string | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  users: Users;
}
